### ISSUE TITLE
License

### ISSUE THREAD

**Issue by trn1ty** [I-Am-Jakoby/Powershell-to-Ducky-Converter#1]
Is there a license on this code? Can it be modified and redistributed or is it proprietary (but open source)?

**Comment by I-Am-Jakoby** [comment]
Open source. Use as you wish. Would be cool if you gave a shout out to this repo if you use it but not required. Goal is to help other people build cool stuff.

**Comment by trn1ty** [comment]
Public domain?

**Comment by I-Am-Jakoby** [comment]
yup that is correct
